insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('1','Álvaro Obregón','OLIVAR DEL CONDE 1RA SECCION','Módulo de participación Ciudadana','Calle 22 esquina calle 17');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('2','Álvaro Obregón','SAN BARTOLO AMEYALCO (PBLO)','Plaza Hidalgo','Calle 8');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('3','Álvaro Obregón','OLIVAR DEL CONDE 2DA SECCION','Mercado Olivar del Conde','Ernesto P. Uruchurtu S/N');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('4','Azcapotzalco','ALDANA','','Calle 26 Esquina Calle 8');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('5','Coyoacán','AJUSCO','','Reyna Ixtlixochitl entre Mixtecas y Toltecas');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('6','Coyoacán','PEDREGAL DE STO DOMINGO','','Ahuanusco entre Jicote y Copal');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('7','Coyoacán','PEDREGAL DE SANTA URSULA','','San Gonzalo entre San Tomas y San Victorio');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('8','Coyoacán','ADOLFO RUIZ CORTINES','','Calmecac esquina Teolole');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('9','Cuauhtémoc','DOCTORES','Jardín de las Artes Gráficas','Dr. Arce y Dr. Agustín Andrade');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('10','Cuauhtémoc','GUERRERO','Estacionamiento del Mercado Martinez de la Torre Anexo','Av. Mosqueta y Degollado');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('11','Gustavo A. Madero','NUEVA ATZACOALCO I II II','','Calle 314  Esquina Calle 316');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('12','Iztapalapa','LOMAS DE SAN LORENZO','Parque Nueva Vida','Calle 3 entre flor de dalia y moras.');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('13','La Magdalena Contreras','Cuauhtémoc','Parque del Caracol','Av. Luis Cabrera');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('14','La Magdalena Contreras','SAN BERNABE OCOTEPEC (PBLO)','','Ayuntamiento esquina. Guerrero');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('15','La Magdalena Contreras','BARROS SIERRA','Deportivo Barros Sierra','Prolongación las Torres');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('16','La Magdalena Contreras','LA MALINCHE','Modulo de Secretaría de Seguridad Ciudadana','Emiliano Zapata Esquina Mariposas');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('17','La Magdalena Contreras','EL TANQUE','Lecheria','Calle Canarios');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('18','La Magdalena Contreras','LAS CRUCES','Modulo de bienestar','Calle Higuera');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('19','Miguel Hidalgo','ANAHUAC','Parque Salesiano','Laguna del Carmen 34');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('20','Miguel Hidalgo','TLAXPANA','Parque Salesiano','Laguna del Carmen 34');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('21','Milpa Alta','SAN SALVADOR CUAUHTENCO (PBLO)','Plaza Civica San Salvador Cuauhtenco','Av. Jalapa esq. Benito Juarez');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('22','Milpa Alta','SAN PABLO OZTOTEPEC (PBLO)','San Pablo Oztotepec frente a mercado','Av. Guerrero esq. Miguel Hidalgo');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('23','Álvaro Obregón','SAN ANTONIO TECOMITL (PBLO)','San Antonio Tecomitl en la Coordinacion Territorial','Av. Morelos esq. Benito Juarez');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('24','Tlahuac','SAN FRANCISCO TLALTENCO (PBLO)','Plaza Centenario','Av. Miguel Hidalgo 4, San Francisco Tlaltenco.');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('25','Tlalpan','SAN MIGUEL TOPILEJO (PBLO)','Kiosco del Pueblo','José Ma Morelos esq Vicente Guerrero');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('26','Tlalpan','EL CAPULIN','Módulo de participación Ciudadana','Miguel Hidalgo esq San Luis Potosí');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('27','Tlalpan','SAN PEDRO MARTIR (PBLO)','Kiosco del pueblo','5 de mayo esq Enseñanza');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('28','Venustiano Carranza','20 DE NOVIEMBRE','Centro Integrador del Bienestar','Electricistas esquina Litografía');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('29','Xochimilco','SAN JOSE ZACATEPEC','Kiosco del pueblo de San Mateo Xalpa','Calle Niños Héroes s/n, San Mateo Xalpa.');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('30','Xochimilco','SAN GREGORIO ATLAPULCO (PBLO)','Plaza Cívica','Cuauhtémoc s/n. Esq con Av. México. San Gregorio Atlapulco');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('31','Xochimilco','SANTA MARIA NATIVITAS (PBLO)','Kiosco del pueblo','José Ma Morelos esq Vicente Guerrero, Santa María Nativitas.');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('32','Xochimilco','SANTA CRUZ ACALPIXCA (PBLO)','Kiosco del pueblo','Lázaro Cardenas s/n esq, con Estudiante.');
insert into colonias_prioritarias(id,alcaldia,colonia,lugar,direccion) values ('33','Xochimilco','SAN LUCAS XOCHIMANCA (PBLO)','Kiosco del pueblo','Monte Carmelo s/n esq. Guadalupe I. Ramírez');