INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3595','17','10','Álvaro Obregón','FRANCISCO LUCAS LUIS JAVIER','FRANCISCO LUCAS LUIS JAVIER','2000');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3599','17','10','Álvaro Obregón','FRANCISCO LUCAS LUIS JAVIER','FRANCISCO LUCAS LUIS JAVIER','2000');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3280','16','10','Álvaro Obregón','TREJO DURAN ABRAHAM','TREJO DURAN ABRAHAM','2001');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3281','16','10','Álvaro Obregón','TREJO DURAN ABRAHAM','TREJO DURAN ABRAHAM','2001');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3303','16','10','Álvaro Obregón','TUNION FIGUEROA DIANA LAURA','TUNION FIGUEROA DIANA LAURA','2002');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3312','16','10','Álvaro Obregón','TUNION FIGUEROA DIANA LAURA','TUNION FIGUEROA DIANA LAURA','2002');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3203','16','10','Álvaro Obregón','MARTINEZ ARIAS ISMAEL','MARTINEZ ARIAS ISMAEL','2003');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3183','16','10','Álvaro Obregón','MARTINEZ ARIAS ISMAEL','MARTINEZ ARIAS ISMAEL','2003');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('71','3','2','Azcapotzalco','BERTHA REYES','BERTHA REYES','2004');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('71','3','2','Azcapotzalco','ANGELES LOPEZ','ANGELES LOPEZ','2005');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('5','8','2','Azcapotzalco','ANGELES LOPEZ','ANGELES LOPEZ','2005');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('208','3','2','Azcapotzalco','NORA SUCHETT','NORA SUCHETT','2006');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('5','8','2','Azcapotzalco','NORA SUCHETT','NORA SUCHETT','2006');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('208','3','2','Azcapotzalco','MARCELO MARTINEZ','MARCELO MARTINEZ','2007');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4411','15','14','Benito Juárez','ADELAIDA DE JESUS AVILA PEREZ','ADELAIDA DE JESUS AVILA PEREZ','2008');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4415','15','14','Benito Juárez','ADELAIDA DE JESUS AVILA PEREZ','ADELAIDA DE JESUS AVILA PEREZ','2008');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4403','15','14','Benito Juárez','FERNANDA KUMASI CORIA PLANCARTE','FERNANDA KUMASI CORIA PLANCARTE','2009');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4380','15','14','Benito Juárez','FERNANDA KUMASI CORIA PLANCARTE','FERNANDA KUMASI CORIA PLANCARTE','2009');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4375','15','14','Benito Juárez','CLAUDIA ACEVEDO MARTINEZ','CLAUDIA ACEVEDO MARTINEZ','2010');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4376','15','14','Benito Juárez','CLAUDIA ACEVEDO MARTINEZ','CLAUDIA ACEVEDO MARTINEZ','2010');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4402','15','14','Benito Juárez','CRISTINA GONZALEZ NAVA','CRISTINA GONZALEZ NAVA','2011');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4407','15','14','Benito Juárez','CRISTINA GONZALEZ NAVA','CRISTINA GONZALEZ NAVA','2011');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('407','23','3','Coyoacán','IVONE MEDINA AGUILAR','IVONE MEDINA AGUILAR','2012');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('418','23','3','Coyoacán','IVONE MEDINA AGUILAR','IVONE MEDINA AGUILAR','2012');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('419','23','3','Coyoacán','LUIS ESTRADA RAMIREZ','LUIS ESTRADA RAMIREZ','2013');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('453','23','3','Coyoacán','LUIS ESTRADA RAMIREZ','LUIS ESTRADA RAMIREZ','2013');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('416','23','3','Coyoacán','LIGIA LOPEZ ROJAS','LIGIA LOPEZ ROJAS','2014');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('382','23','3','Coyoacán','LIGIA LOPEZ ROJAS','LIGIA LOPEZ ROJAS','2014');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('560','24','3','Coyoacán','CARLOS ROSAS TREJO','CARLOS ROSAS TREJO','2015');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('591','24','3','Coyoacán','MA LUISA CRUZ DE JESUS','MA LUISA CRUZ DE JESUS','2016');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('594','24','3','Coyoacán','MA LUISA CRUZ DE JESUS','MA LUISA CRUZ DE JESUS','2016');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('819','17','4','Cuajimalpa de Morelos','MARISOL PACHECO DIAZ','MARISOL PACHECO DIAZ','2017');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('818','17','4','Cuajimalpa de Morelos','MARISOL PACHECO DIAZ','MARISOL PACHECO DIAZ','2017');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('817','17','4','Cuajimalpa de Morelos','MARISOL PACHECO DIAZ','MARISOL PACHECO DIAZ','2017');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('808','17','4','Cuajimalpa de Morelos','BENJAMIN ARIAS ALONSO','BENJAMIN ARIAS ALONSO','2018');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('809','17','4','Cuajimalpa de Morelos','BENJAMIN ARIAS ALONSO','BENJAMIN ARIAS ALONSO','2018');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('810','17','4','Cuajimalpa de Morelos','BENJAMIN ARIAS ALONSO','BENJAMIN ARIAS ALONSO','2018');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('807','17','4','Cuajimalpa de Morelos','CAROLINA ESTRADA GOMEZ','CAROLINA ESTRADA GOMEZ','2019');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('806','17','4','Cuajimalpa de Morelos','CAROLINA ESTRADA GOMEZ','CAROLINA ESTRADA GOMEZ','2019');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('755','17','4','Cuajimalpa de Morelos','ALAN YAIR MEJIA ALCAZAR','ALAN YAIR MEJIA ALCAZAR','2020');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('756','17','4','Cuajimalpa de Morelos','ALAN YAIR MEJIA ALCAZAR','ALAN YAIR MEJIA ALCAZAR','2020');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('757','17','4','Cuajimalpa de Morelos','ALAN YAIR MEJIA ALCAZAR','ALAN YAIR MEJIA ALCAZAR','2020');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('813','17','4','Cuajimalpa de Morelos','EDGAR POZAS GRANADOS','EDGAR POZAS GRANADOS','2021');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('812','17','4','Cuajimalpa de Morelos','EDGAR POZAS GRANADOS','EDGAR POZAS GRANADOS','2021');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('763','17','4','Cuajimalpa de Morelos','KELVIN URIEL ROQUE GONZALEZ','KELVIN URIEL ROQUE GONZALEZ','2022');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('762','17','4','Cuajimalpa de Morelos','KELVIN URIEL ROQUE GONZALEZ','KELVIN URIEL ROQUE GONZALEZ','2022');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4800','12','15','Cuauhtémoc','MELENDEZ HERNANDEZ TRINIDAD ALMENDRA','MELENDEZ HERNANDEZ TRINIDAD ALMENDRA','2023');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4806','12','15','Cuauhtémoc','SANCHÉZ WINDFIELD GUSTAVO','SANCHÉZ WINDFIELD GUSTAVO','2024');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4700','8','15','Cuauhtémoc','LUNA GARCÍA PATRICIA','LUNA GARCÍA PATRICIA','2025');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4697','8','15','Cuauhtémoc','LARA BÉNITEZ VERONICA','LARA BÉNITEZ VERONICA','2026');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4557','12','15','Cuauhtémoc','GARCÍA AGUILAR NORMA ANGELICA','GARCÍA AGUILAR NORMA ANGELICA','2027');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4577','12','15','Cuauhtémoc','RÚIZ GUTIERREZ AXEL','RÚIZ GUTIERREZ AXEL','2028');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('1494','2','5','Gustavo A. Madero','VARGAS SOLIS ADRIANA','VARGAS SOLIS ADRIANA','2029');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('1491','2','5','Gustavo A. Madero','VERA GONZALEZ GERARDO DANIEL','VERA GONZALEZ GERARDO DANIEL','2030');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('1487','2','5','Gustavo A. Madero','GARCIA RIVERA GERARDO MISHAEL','GARCIA RIVERA GERARDO MISHAEL','2031');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('1488','2','5','Gustavo A. Madero','RUVALCABA MOTA RAQUEL ADRIANA','RUVALCABA MOTA RAQUEL ADRIANA','2032');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('1771','13','6','Iztacalco','JUANA ESPINOZA HERNANDEZ','JUANA ESPINOZA HERNANDEZ','2033');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('1777','13','6','Iztacalco','JESUS MENDOZA','JESUS MENDOZA','2034');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('1778','13','6','Iztacalco','JESUS MENDOZA','JESUS MENDOZA','2034');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('1813','13','6','Iztacalco','JESSICA PAOLA RODRIGUEZ','JESSICA PAOLA RODRIGUEZ','2035');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('1829','13','6','Iztacalco','JULIA MARCOS HERNANDEZ','JULIA MARCOS HERNANDEZ','2036');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('1776','13','6','Iztacalco','JULIA MARCOS HERNANDEZ','JULIA MARCOS HERNANDEZ','2036');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('2908','25','7','Iztapalapa','OJEDA SALAZAR SANDRA LUZ','OJEDA SALAZAR SANDRA LUZ','2037');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('2909','25','7','Iztapalapa','OJEDA SALAZAR SANDRA LUZ','OJEDA SALAZAR SANDRA LUZ','2037');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('2921','25','7','Iztapalapa','VALDEZ NOGUERON PATRICIA','VALDEZ NOGUERON PATRICIA','2038');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('2922','25','7','Iztapalapa','VALDEZ NOGUERON PATRICIA','VALDEZ NOGUERON PATRICIA','2038');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('2924','25','7','Iztapalapa','HERRERA RANGEL JOSE DANIEL','HERRERA RANGEL JOSE DANIEL','2039');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('2925','25','7','Iztapalapa','HERRERA RANGEL JOSE DANIEL','HERRERA RANGEL JOSE DANIEL','2039');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('2944','25','7','Iztapalapa','MANZANO ALTAMIRANO MARICELA','MANZANO ALTAMIRANO MARICELA','2040');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('2948','25','7','Iztapalapa','MANZANO ALTAMIRANO MARICELA','MANZANO ALTAMIRANO MARICELA','2040');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3015','26','8','La Magdalena Contreras','ANA MARIA CASAS MIRANDA','ANA MARIA CASAS MIRANDA','2041');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('2988','26','8','La Magdalena Contreras','YENDI LUCERO ROCHA CASTRO','YENDI LUCERO ROCHA CASTRO','2042');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3102','26','8','La Magdalena Contreras','ANA LILIA BEIMONT TAPIA','ANA LILIA BEIMONT TAPIA','2043');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3107','26','8','La Magdalena Contreras','ROSA MILLAN HUERTA','ROSA MILLAN HUERTA','2044');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3011','26','8','La Magdalena Contreras','ARMANDO SOUZA ERREGUÍN','ARMANDO SOUZA ERREGUÍN','2045');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('5138','10','16','Miguel Hidalgo','LEON ESPINOSA NANCY VIRIDIANA','LEON ESPINOSA NANCY VIRIDIANA','2046');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('5142','10','16','Miguel Hidalgo','LEON ESPINOSA NANCY VIRIDIANA','LEON ESPINOSA NANCY VIRIDIANA','2046');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('5140','10','16','Miguel Hidalgo','MENDOZA SANCHEZ FRANCISCO ARTURO','MENDOZA SANCHEZ FRANCISCO ARTURO','2047');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('5141','10','16','Miguel Hidalgo','MENDOZA SANCHEZ FRANCISCO ARTURO','MENDOZA SANCHEZ FRANCISCO ARTURO','2047');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('5121','10','16','Miguel Hidalgo','MEDINA NIETO RICARDO','MEDINA NIETO RICARDO','2048');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('5122','10','16','Miguel Hidalgo','MEDINA NIETO RICARDO','MEDINA NIETO RICARDO','2048');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('5123','10','16','Miguel Hidalgo','VELAZQUEZ BRAVO MARCOS FERNANDO','VELAZQUEZ BRAVO MARCOS FERNANDO','2049');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('5124','10','16','Miguel Hidalgo','VELAZQUEZ BRAVO MARCOS FERNANDO','VELAZQUEZ BRAVO MARCOS FERNANDO','2049');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3127','21','9','Milpa Alta','NATALY CHORA HERNANDEZ','NATALY CHORA HERNANDEZ','2050');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3127','21','9','Milpa Alta','AUREA ROSAS TABARES','AUREA ROSAS TABARES','2051');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3128','21','9','Milpa Alta','LOURDES ALVARADO GALLARDO','LOURDES ALVARADO GALLARDO','2052');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3128','21','9','Milpa Alta','YANIN REYES ACEVEDO','YANIN REYES ACEVEDO','2053');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3676','27','11','Tlahuac','EDUARDO SOTELO MARTINEZ','EDUARDO SOTELO MARTINEZ','2054');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3677','27','11','Tlahuac','EDUARDO SOTELO MARTINEZ','EDUARDO SOTELO MARTINEZ','2054');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3681','27','11','Tlahuac','ANA LAURA SANDOVAL BAUTISTA','ANA LAURA SANDOVAL BAUTISTA','2055');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3682','27','11','Tlahuac','ANA LAURA SANDOVAL BAUTISTA','ANA LAURA SANDOVAL BAUTISTA','2055');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3629','27','11','Tlahuac','LUIS RAMIREZ GARCIA','LUIS RAMIREZ GARCIA','2056');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3628','27','11','Tlahuac','LUIS RAMIREZ GARCIA','LUIS RAMIREZ GARCIA','2056');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3630','27','11','Tlahuac','ANTONIO BENJAMIN CAMPOS PEREZ','ANTONIO BENJAMIN CAMPOS PEREZ','2057');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3653','27','11','Tlahuac','ANTONIO BENJAMIN CAMPOS PEREZ','ANTONIO BENJAMIN CAMPOS PEREZ','2057');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3891','14','12','Tlalpan','CLAUDIA NAVARRO HERNÁNDEZ','CLAUDIA NAVARRO HERNÁNDEZ','2058');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3905','5','12','Tlalpan','CLAUDIA NAVARRO HERNÁNDEZ','CLAUDIA NAVARRO HERNÁNDEZ','2058');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3916','14','12','Tlalpan','ALEJANDRA YAZMIN PACHECO','ALEJANDRA YAZMIN PACHECO','2059');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3918','14','12','Tlalpan','ALEJANDRA YAZMIN PACHECO','ALEJANDRA YAZMIN PACHECO','2059');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3907','14','12','Tlalpan','LUIS FRANCISCO MIGUEL','LUIS FRANCISCO MIGUEL','2060');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3890','14','12','Tlalpan','LUIS FRANCISCO MIGUEL','LUIS FRANCISCO MIGUEL','2060');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3917','14','12','Tlalpan','PAOLA RAMIREZ SOSA','PAOLA RAMIREZ SOSA','2061');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('3915','5','12','Tlalpan','PAOLA RAMIREZ SOSA','PAOLA RAMIREZ SOSA','2061');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('5184','9','17','Venustiano Carranza','MARTINEZ ROMERO VICTOR HUGO','MARTINEZ ROMERO VICTOR HUGO','2062');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('5185','9','17','Venustiano Carranza','JIMENEZ CAPIZ ELEANE','JIMENEZ CAPIZ ELEANE','2063');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('5186','9','17','Venustiano Carranza','LUNA HERNANDEZ JOSE MIGUEL','LUNA HERNANDEZ JOSE MIGUEL','2064');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('5187','9','17','Venustiano Carranza','GUTIERREZ GARCIA JORGE','GUTIERREZ GARCIA JORGE','2065');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4252','9','13','Xochimilco','ALVARADO MEDINA JOSE ARTURO','ALVARADO MEDINA JOSE ARTURO','2066');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4175','9','13','Xochimilco','VANEGAS CONTRERAS DAMARIS','VANEGAS CONTRERAS DAMARIS','2067');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4174','9','13','Xochimilco','LOPEZ PELCASTRE MARIBEL','LOPEZ PELCASTRE MARIBEL','2068');
INSERT INTO datos (seccion, distrito, municipio, delegacion, equipo, coordinador,usuario) VALUES ('4255','9','13','Xochimilco','LOPEZ MALDONADO EDMUNDA','LOPEZ MALDONADO EDMUNDA','2069');
